# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CICD for EcomInventory

on:
  push:
    branches: [ "main" ]
jobs:
  build:

    runs-on: ubuntu-latest 

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: npm install and build
        run: 
          npm --version
          echo npm --version
        env: 
          CI: true

  # deploy:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Set up SSH
  #       uses: webfactory/ssh-agent@v0.4.1
  #       with:
  #         ssh-private-key: ${{ secrets.KEY }}

  #     - name: SSH into Remote Server and Execute Script
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.HOST}}
  #         username: ${{ secrets.USER}}
  #         key: ${{ secrets.KEY }}
  #         port: 22
  #         script: |

  #           cd ~/EcomInventory/frontend/EcomInventory  
  #           # Execute the remote script
  #           git pull origin main

  #         # Optional: Capture output to a log file
  #         out: deployment.log


  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:

     - name: SSH deploy
       uses: appleboy/ssh-action@master
       with:
          host: ${{ secrets.HOST}}
          username: ${{ secrets.USER}}
          key: ${{ secrets.KEY}}
          port:  22
          script: |


            cd ~/EcomInventory/frontend/EcomInventory  
            # Execute the remote script
            git pull origin main