# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CICD for EcomInventory

on:
  push:
    branches: [ "main" ]

jobs:      
  deploy: 
    runs-on: ubuntu-latest 
    steps:
     - name: SSH deploy
       uses: appleboy/ssh-action@master
       with:
          host: ${{ secrets.HOST }}
          username:  ${{ secrets.USER }}
          key:  ${{ secrets.KEY }}
          port: 22
          script: |
            cd ~/EcomInventory/frontend/EcomInventory  
            # Execute the remote script
            git pull origin main
          

            
