# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CICD for EcomInventory

on:
  push:
    branches: [ "main" ]

jobs:

  pull:
    runs-on: ubuntu-latest
    steps:
     - name: SSH deploy
       uses: appleboy/ssh-action@v0.1.4
       with:
          host: ${{ secrets.HOST}}
          username: ${{ secrets.USER}}
          key: ${{ secrets.KEY}}
          port:  22
          script: |

            cd ~/EcomInventory/frontend/EcomInventory  
            # Execute the remote script
            git pull origin main

  build:
    needs: [pull]
    runs-on: ubuntu-latest 

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: npm install and build
        run: 
          npm --version
          echo npm --version
          npm install
          npm install -g pm2
        env: 
          CI: true
  
  deploy: 
    needs: [build]
    runs-on: ubuntu-latest 
    env:
     SSH_KEY: ${{ secrets.KEY}}
    steps:
    - name: SSH deploy
      run: |
        echo "$SSH_KEY" > /tmp/ssh_key
        chmod 600 /tmp/ssh_key
        ssh -i /tmp/ssh_key -o StrictHostKeyChecking=no -v ubuntu@16.171.204.236 'bash ~/restart.sh' 
        rm -r /tmp/ssh_key
  
